services:
  - type: web
    name: cloud-storage-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --bind 0.0.0.0:$PORT run:app
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: OTP_EXPIRY
        value: 180
      - key: PYTHON_VERSION
        value: 3.11.0
